packages:
  - service
  - web
  - admin
  - app
  - packages/*

catalog:
  '@ant-design/icons': ^5.3.0
  '@commitlint/cli': ^18.4.3
  '@commitlint/config-conventional': ^18.4.3
  '@formily/antd-v5': ^1.2.4
  '@formily/core': ^2.3.7
  '@formily/react': ^2.3.7
  '@formily/reactive': ^2.3.7
  '@formily/reactive-react': ^2.3.7
  '@formily/validator': ^2.3.7
  '@nestjs/bull': ^10.0.1
  '@nestjs/cache-manager': ^2.1.1
  '@nestjs/cli': ^10.2.1
  '@nestjs/common': ^10.3.0
  '@nestjs/config': ^3.1.1
  '@nestjs/core': ^10.3.0
  '@nestjs/event-emitter': ^2.0.3
  '@nestjs/jwt': ^10.2.0
  '@nestjs/passport': ^10.0.3
  '@nestjs/platform-express': ^10.3.0
  '@nestjs/platform-socket.io': ^11.1.8
  '@nestjs/schedule': ^4.0.0
  '@nestjs/schematics': ^10.0.3
  '@nestjs/swagger': ^7.1.17
  '@nestjs/testing': ^10.3.0
  '@nestjs/throttler': ^5.1.1
  '@nestjs/typeorm': ^10.0.1
  '@nestjs/websockets': ^11.1.8
  '@tailwindcss/typography': ^0.5.19
  '@tanstack/react-query': ^5.17.0
  '@tanstack/react-query-devtools': ^5.90.2
  '@types/bcrypt': ^5.0.2
  '@types/express': ^4.17.21
  '@types/jest': ^29.5.11
  '@types/lodash': ^4.14.202
  '@types/lodash-es': ^4.17.12
  '@types/multer': ^1.4.11
  '@types/node': ^20.19.24
  '@types/passport-github2': ^1.2.9
  '@types/passport-jwt': ^4.0.0
  '@types/passport-local': ^1.0.38
  '@types/react': ^18.2.45
  '@types/react-dom': ^18.2.18
  '@types/supertest': ^6.0.2
  '@types/uuid': ^9.0.7
  '@typescript-eslint/eslint-plugin': ^6.15.0
  '@typescript-eslint/parser': ^6.15.0
  antd: ^5.20.0
  autoprefixer: ^10.4.16
  axios: ^1.6.2
  bcrypt: 5.1.1
  bull: ^4.12.0
  cache-manager: ^5.3.2
  cache-manager-redis-yet: ^4.1.2
  class-transformer: ^0.5.1
  class-validator: ^0.14.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.0
  dayjs: ^1.11.10
  dotenv: ^17.2.3
  eslint: ^8.56.0
  eslint-config-next: ^14.0.4
  express: ^5.1.0
  husky: ^8.0.3
  jest: ^29.7.0
  lint-staged: ^15.2.0
  lodash: ^4.17.21
  lodash-es: ^4.17.21
  multer: ^1.4.5-lts.1
  nest-winston: ^1.9.4
  nestjs-i18n: ^10.5.1
  next: ^14.0.4
  passport: ^0.7.0
  passport-custom: ^1.1.1
  passport-github2: ^0.1.12
  passport-jwt: ^4.0.1
  passport-local: ^1.0.0
  pg: ^8.11.3
  postcss: ^8.4.32
  react: ^18.2.0
  react-dom: ^18.2.0
  redis: ^4.6.12
  reflect-metadata: ^0.1.13
  rimraf: ^5.0.5
  rxjs: ^7.8.1
  sharp: ^0.33.1
  socket.io: ^4.8.1
  socket.io-client: ^4.8.1
  source-map-support: ^0.5.21
  supertest: ^6.3.3
  tailwindcss: ^3.4.1
  ts-jest: ^29.1.1
  ts-loader: ^9.5.1
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  turbo: ^1.11.2
  typeorm: ^0.3.17
  typescript: ^5.3.3
  uuid: ^9.0.1
  winston: ^3.11.0
  zod: ^3.22.4
  zustand: ^4.4.7

onlyBuiltDependencies:
  - bcrypt
